In [74]:
import pandas as pd
import matplotlib.pyplot as plt
db6 = pd.read_csv(r'/Users/minhnguyetnguyen/Documents/AISOUP/AutoML/Database/DB6/wpbc.csv')
db6

,119513,N,31,18.02,27.6,117.5,1013,0.09489,0.1036,0.1086,...,139.7,1436,0.1195,0.1926,0.314,0.117,0.2677,0.08113,5,5.1
0,8423,N,61,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,...,184.60,2019.0,0.16220,0.6656,0.7119,0.26540,0.4601,0.11890,3.0,2
1,842517,N,116,21.37,17.44,137.50,1373.0,0.08836,0.11890,0.12550,...,159.10,1949.0,0.11880,0.3449,0.3414,0.20320,0.4334,0.09067,2.5,0
2,843483,N,123,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,...,98.87,567.7,0.20980,0.8663,0.6869,0.25750,0.6638,0.17300,2.0,0
3,843584,R,27,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,...,152.20,1575.0,0.13740,0.2050,0.4000,0.16250,0.2364,0.07678,3.5,0
4,843786,R,77,12.75,15.29,84.60,502.7,0.11890,0.15690,0.16640,...,107.30,733.2,0.17060,0.4196,0.5999,0.17090,0.3485,0.11790,2.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,942640,N,10,22.52,21.92,146.90,1597.0,0.07592,0.09162,0.06862,...,162.10,1902.0,0.08191,0.1319,0.1056,0.09378,0.2061,0.05788,6.0,2
193,943471,N,8,15.44,31.18,101.00,740.4,0.09399,0.10620,0.13750,...,112.60,929.0,0.12720,0.2362,0.2975,0.12860,0.2914,0.08024,1.5,0
194,94547,N,12,17.17,29.19,110.00,915.3,0.08952,0.06655,0.06583,...,132.50,1295.0,0.12610,0.1572,0.2141,0.09520,0.3362,0.06033,3.7,0
195,947204,R,3,21.42,22.84,145.00,1440.0,0.10700,0.19390,0.23800,...,198.30,2375.0,0.14980,0.4379,0.5411,0.22150,0.2832,0.08981,3.0,?
196,947489,N,6,16.70,28.13,110.30,885.4,0.08896,0.11310,0.10120,...,128.80,1213.0,0.13300,0.2808,0.3455,0.13170,0.3035,0.08036,3.5,0

In [75]:
db6_txt = pd.read_table(r'/Users/minhnguyetnguyen/Documents/AISOUP/AutoML/Database/DB6/wpbc.csv')
db6_txt

    119513,N,31,18.02,27.6,117.5,1013,0.09489,0.1036,0.1086,0.07055,0.1865,0.06333,0.6249,1.89,3.972,71.55,0.004433,0.01421,0.03233,0.009854,0.01694,0.003495,21.63,37.08,139.7,1436,0.1195,0.1926,0.314,0.117,0.2677,0.08113,5,5
0    8423,N,61,17.99,10.38,122.8,1001,0.1184,0.2776...
1    842517,N,116,21.37,17.44,137.5,1373,0.08836,0....
2    843483,N,123,11.42,20.38,77.58,386.1,0.1425,0....
3    843584,R,27,20.29,14.34,135.1,1297,0.1003,0.13...
4    843786,R,77,12.75,15.29,84.6,502.7,0.1189,0.15...
..                                                 ...
192  942640,N,10,22.52,21.92,146.9,1597,0.07592,0.0...
193  943471,N,8,15.44,31.18,101,740.4,0.09399,0.106...
194  94547,N,12,17.17,29.19,110,915.3,0.08952,0.066...
195  947204,R,3,21.42,22.84,145,1440,0.107,0.1939,0...
196  947489,N,6,16.7,28.13,110.3,885.4,0.08896,0.11...

[197 rows x 1 columns]

In [76]:
# Get the column names as a list
columns = db6.columns.tolist()

# Move the second column to the end
second_column = columns.pop(1)
columns.append(second_column)

# Reorder the columns in the DataFrame
db6 = db6[columns]
db6

,119513,31,18.02,27.6,117.5,1013,0.09489,0.1036,0.1086,0.07055,...,1436,0.1195,0.1926,0.314,0.117,0.2677,0.08113,5,5.1,N
0,8423,61,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,2019.0,0.16220,0.6656,0.7119,0.26540,0.4601,0.11890,3.0,2,N
1,842517,116,21.37,17.44,137.50,1373.0,0.08836,0.11890,0.12550,0.08180,...,1949.0,0.11880,0.3449,0.3414,0.20320,0.4334,0.09067,2.5,0,N
2,843483,123,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,567.7,0.20980,0.8663,0.6869,0.25750,0.6638,0.17300,2.0,0,N
3,843584,27,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,1575.0,0.13740,0.2050,0.4000,0.16250,0.2364,0.07678,3.5,0,R
4,843786,77,12.75,15.29,84.60,502.7,0.11890,0.15690,0.16640,0.07666,...,733.2,0.17060,0.4196,0.5999,0.17090,0.3485,0.11790,2.5,0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,942640,10,22.52,21.92,146.90,1597.0,0.07592,0.09162,0.06862,0.06367,...,1902.0,0.08191,0.1319,0.1056,0.09378,0.2061,0.05788,6.0,2,N
193,943471,8,15.44,31.18,101.00,740.4,0.09399,0.10620,0.13750,0.06500,...,929.0,0.12720,0.2362,0.2975,0.12860,0.2914,0.08024,1.5,0,N
194,94547,12,17.17,29.19,110.00,915.3,0.08952,0.06655,0.06583,0.05068,...,1295.0,0.12610,0.1572,0.2141,0.09520,0.3362,0.06033,3.7,0,N
195,947204,3,21.42,22.84,145.00,1440.0,0.10700,0.19390,0.23800,0.13180,...,2375.0,0.14980,0.4379,0.5411,0.22150,0.2832,0.08981,3.0,?,R
196,947489,6,16.70,28.13,110.30,885.4,0.08896,0.11310,0.10120,0.04989,...,1213.0,0.13300,0.2808,0.3455,0.13170,0.3035,0.08036,3.5,0,N

In [77]:
# Extract column names from the DataFrame
column_names = db6.columns.tolist()

# Create a new DataFrame with the duplicated column names as the first row
new_row = pd.DataFrame([column_names], columns=db6.columns)

# Concatenate the new row and the rest of the data
db6 = pd.concat([new_row, db6], ignore_index=True)
# Rename the column names
new_column_names = [f"X.{i}" for i in range(len(column_names) - 1)] + ["Class"] 
db6.columns = new_column_names
# Convert all columns except "Class" to numeric data types
for column in db6.columns:
    if column != "Class":
        db6[column] = pd.to_numeric(db6[column], errors="coerce")
db6

,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,...,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33,Class
0,119513,31,18.02,27.60,117.50,1013.0,0.09489,0.10360,0.10860,0.07055,...,1436.0,0.11950,0.1926,0.3140,0.11700,0.2677,0.08113,5.0,5.1,N
1,8423,61,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,2019.0,0.16220,0.6656,0.7119,0.26540,0.4601,0.11890,3.0,2.0,N
2,842517,116,21.37,17.44,137.50,1373.0,0.08836,0.11890,0.12550,0.08180,...,1949.0,0.11880,0.3449,0.3414,0.20320,0.4334,0.09067,2.5,0.0,N
3,843483,123,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,567.7,0.20980,0.8663,0.6869,0.25750,0.6638,0.17300,2.0,0.0,N
4,843584,27,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,1575.0,0.13740,0.2050,0.4000,0.16250,0.2364,0.07678,3.5,0.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,942640,10,22.52,21.92,146.90,1597.0,0.07592,0.09162,0.06862,0.06367,...,1902.0,0.08191,0.1319,0.1056,0.09378,0.2061,0.05788,6.0,2.0,N
194,943471,8,15.44,31.18,101.00,740.4,0.09399,0.10620,0.13750,0.06500,...,929.0,0.12720,0.2362,0.2975,0.12860,0.2914,0.08024,1.5,0.0,N
195,94547,12,17.17,29.19,110.00,915.3,0.08952,0.06655,0.06583,0.05068,...,1295.0,0.12610,0.1572,0.2141,0.09520,0.3362,0.06033,3.7,0.0,N
196,947204,3,21.42,22.84,145.00,1440.0,0.10700,0.19390,0.23800,0.13180,...,2375.0,0.14980,0.4379,0.5411,0.22150,0.2832,0.08981,3.0,NaN,R
197,947489,6,16.70,28.13,110.30,885.4,0.08896,0.11310,0.10120,0.04989,...,1213.0,0.13300,0.2808,0.3455,0.13170,0.3035,0.08036,3.5,0.0,N

In [78]:
# Change specific values in the DataFrame
db6.at[0, 'X.33'] = 5.0
db6

,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,...,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33,Class
0,119513,31,18.02,27.60,117.50,1013.0,0.09489,0.10360,0.10860,0.07055,...,1436.0,0.11950,0.1926,0.3140,0.11700,0.2677,0.08113,5.0,5.0,N
1,8423,61,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,2019.0,0.16220,0.6656,0.7119,0.26540,0.4601,0.11890,3.0,2.0,N
2,842517,116,21.37,17.44,137.50,1373.0,0.08836,0.11890,0.12550,0.08180,...,1949.0,0.11880,0.3449,0.3414,0.20320,0.4334,0.09067,2.5,0.0,N
3,843483,123,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,567.7,0.20980,0.8663,0.6869,0.25750,0.6638,0.17300,2.0,0.0,N
4,843584,27,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,1575.0,0.13740,0.2050,0.4000,0.16250,0.2364,0.07678,3.5,0.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,942640,10,22.52,21.92,146.90,1597.0,0.07592,0.09162,0.06862,0.06367,...,1902.0,0.08191,0.1319,0.1056,0.09378,0.2061,0.05788,6.0,2.0,N
194,943471,8,15.44,31.18,101.00,740.4,0.09399,0.10620,0.13750,0.06500,...,929.0,0.12720,0.2362,0.2975,0.12860,0.2914,0.08024,1.5,0.0,N
195,94547,12,17.17,29.19,110.00,915.3,0.08952,0.06655,0.06583,0.05068,...,1295.0,0.12610,0.1572,0.2141,0.09520,0.3362,0.06033,3.7,0.0,N
196,947204,3,21.42,22.84,145.00,1440.0,0.10700,0.19390,0.23800,0.13180,...,2375.0,0.14980,0.4379,0.5411,0.22150,0.2832,0.08981,3.0,NaN,R
197,947489,6,16.70,28.13,110.30,885.4,0.08896,0.11310,0.10120,0.04989,...,1213.0,0.13300,0.2808,0.3455,0.13170,0.3035,0.08036,3.5,0.0,N

In [79]:
db6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X.0     198 non-null    int64
 1   X.1     198 non-null    int64
 2   X.2     198 non-null    float64
 3   X.3     198 non-null    float64
 4   X.4     198 non-null    float64
 5   X.5     198 non-null    float64
 6   X.6     198 non-null    float64
 7   X.7     198 non-null    float64
 8   X.8     198 non-null    float64
 9   X.9     198 non-null    float64
 10  X.10    198 non-null    float64
 11  X.11    198 non-null    float64
 12  X.12    198 non-null    float64
 13  X.13    198 non-null    float64
 14  X.14    198 non-null    float64
 15  X.15    198 non-null    float64
 16  X.16    198 non-null    float64
 17  X.17    198 non-null    float64
 18  X.18    198 non-null    float64
 19  X.19    198 non-null    float64
 20  X.20    198 non-null    float64
 21  X.21    198 non-null    float64
 22  X.22    198 non-null    float64
 23  X.23    198 non-null    float64
 24  X.24    198 non-null    float64
 25  X.25    198 non-null    float64
 26  X.26    198 non-null    float64
 27  X.27    198 non-null    float64
 28  X.28    198 non-null    float64
 29  X.29    198 non-null    float64
 30  X.30    198 non-null    float64
 31  X.31    198 non-null    float64
 32  X.32    198 non-null    float64
 33  X.33    194 non-null    float64
 34  Class   198 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 54.3+ KB

In [80]:
db6.isna().sum()

X.0      0
X.1      0
X.2      0
X.3      0
X.4      0
X.5      0
X.6      0
X.7      0
X.8      0
X.9      0
X.10     0
X.11     0
X.12     0
X.13     0
X.14     0
X.15     0
X.16     0
X.17     0
X.18     0
X.19     0
X.20     0
X.21     0
X.22     0
X.23     0
X.24     0
X.25     0
X.26     0
X.27     0
X.28     0
X.29     0
X.30     0
X.31     0
X.32     0
X.33     4
Class    0
dtype: int64

In [81]:
db6 = db6.dropna()
# Reset the index
db6 = db6.reset_index(drop=True)
db6

,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,...,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33,Class
0,119513,31,18.02,27.60,117.50,1013.0,0.09489,0.10360,0.10860,0.07055,...,1436.0,0.11950,0.1926,0.3140,0.11700,0.2677,0.08113,5.0,5.0,N
1,8423,61,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,2019.0,0.16220,0.6656,0.7119,0.26540,0.4601,0.11890,3.0,2.0,N
2,842517,116,21.37,17.44,137.50,1373.0,0.08836,0.11890,0.12550,0.08180,...,1949.0,0.11880,0.3449,0.3414,0.20320,0.4334,0.09067,2.5,0.0,N
3,843483,123,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,567.7,0.20980,0.8663,0.6869,0.25750,0.6638,0.17300,2.0,0.0,N
4,843584,27,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,1575.0,0.13740,0.2050,0.4000,0.16250,0.2364,0.07678,3.5,0.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,9411300,3,14.72,25.26,99.28,657.5,0.11740,0.21120,0.17290,0.09465,...,814.8,0.14640,0.5352,0.5655,0.19740,0.3778,0.11320,1.7,21.0,N
190,942640,10,22.52,21.92,146.90,1597.0,0.07592,0.09162,0.06862,0.06367,...,1902.0,0.08191,0.1319,0.1056,0.09378,0.2061,0.05788,6.0,2.0,N
191,943471,8,15.44,31.18,101.00,740.4,0.09399,0.10620,0.13750,0.06500,...,929.0,0.12720,0.2362,0.2975,0.12860,0.2914,0.08024,1.5,0.0,N
192,94547,12,17.17,29.19,110.00,915.3,0.08952,0.06655,0.06583,0.05068,...,1295.0,0.12610,0.1572,0.2141,0.09520,0.3362,0.06033,3.7,0.0,N
193,947489,6,16.70,28.13,110.30,885.4,0.08896,0.11310,0.10120,0.04989,...,1213.0,0.13300,0.2808,0.3455,0.13170,0.3035,0.08036,3.5,0.0,N

In [82]:
# List of column names to check (exclude the "Class" column)
columns_to_check = [col for col in db6.columns if col != 'Class']

# Use applymap and str.isdigit to check if data in each cell is a digit
is_digit_df = db6[columns_to_check].applymap(lambda x: str(x).isdigit())

# Check if all columns have all digits (True) or not (False)
are_all_digits = is_digit_df.all()

# Display which columns contain non-digits
non_digit_columns = are_all_digits[~are_all_digits].index.tolist()
non_digit_columns

['X.2',
 'X.3',
 'X.4',
 'X.5',
 'X.6',
 'X.7',
 'X.8',
 'X.9',
 'X.10',
 'X.11',
 'X.12',
 'X.13',
 'X.14',
 'X.15',
 'X.16',
 'X.17',
 'X.18',
 'X.19',
 'X.20',
 'X.21',
 'X.22',
 'X.23',
 'X.24',
 'X.25',
 'X.26',
 'X.27',
 'X.28',
 'X.29',
 'X.30',
 'X.31',
 'X.32',
 'X.33']

In [83]:
db6.describe()

,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,...,X.24,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33
count,1.940000e+02,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,...,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000
mean,2.013348e+06,46.938144,17.402320,22.300979,114.781495,969.092268,0.102774,0.142642,0.156309,0.086808,...,140.136907,1401.756701,0.143921,0.364567,0.436010,0.178449,0.322251,0.090777,2.867526,3.211340
std,2.914339e+06,34.523646,3.171672,4.335292,21.430694,353.159959,0.012607,0.050229,0.070942,0.033962,...,28.826843,587.040705,0.022092,0.165528,0.174757,0.045529,0.074068,0.021371,1.950588,5.479276
min,8.423000e+03,1.000000,10.950000,10.380000,71.900000,361.600000,0.074970,0.046050,0.023980,0.020310,...,85.100000,508.100000,0.081910,0.051310,0.023980,0.028990,0.156500,0.055040,0.400000,0.000000
25%,8.561758e+05,14.250000,15.052500,19.342500,98.160000,702.525000,0.093900,0.109850,0.106075,0.063760,...,117.925000,940.575000,0.129325,0.247550,0.322150,0.152225,0.275950,0.076368,1.500000,0.000000
50%,8.864710e+05,39.500000,17.290000,21.795000,113.700000,929.100000,0.102200,0.131750,0.152050,0.086075,...,136.500000,1295.000000,0.141750,0.350450,0.401150,0.178500,0.310300,0.086540,2.500000,1.000000
75%,9.279958e+05,73.000000,19.580000,24.782500,129.650000,1193.500000,0.111375,0.172200,0.200500,0.103925,...,159.875000,1694.250000,0.154450,0.423675,0.550175,0.207125,0.358475,0.101775,3.500000,4.000000
max,9.411300e+06,125.000000,27.220000,39.280000,182.100000,2250.000000,0.144700,0.311400,0.426800,0.201200,...,232.200000,3903.000000,0.222600,1.058000,1.170000,0.290300,0.663800,0.207500,10.000000,27.000000

In [84]:
db6.to_csv(r'/Users/minhnguyetnguyen/Documents/AISOUP/AutoML/Database/DB6/db6.csv', index=False)

In [85]:
db6['Class'].value_counts()

N    148
R     46
Name: Class, dtype: int64

In [86]:
from sklearn.preprocessing import StandardScaler
# Extract the features from the DataFrame
features = db6.drop(columns=['Class'])

# Initialize the StandardScaler
scaler = StandardScaler()

# Perform data standardization on the features
features_standardized = scaler.fit_transform(features)

# Convert the standardized features back to a DataFrame
features_standardized_df = pd.DataFrame(features_standardized, columns=features.columns)

# Combine the standardized features with the 'Class' column
db6_standardized = pd.concat([db6['Class'], features_standardized_df], axis=1)
db6_standardized

,Class,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,...,X.24,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33
0,N,-0.651515,-0.462853,0.195253,1.225461,0.127179,0.124650,-0.627033,-0.779281,-0.674251,...,-0.015195,0.058483,-1.108262,-1.041587,-0.699976,-1.353154,-0.738394,-0.452563,1.096075,0.327286
1,N,-0.689732,0.408365,0.185770,-2.756867,0.375128,0.090583,1.242682,2.693812,2.032129,...,1.546411,1.054169,0.829555,1.823322,1.582786,1.914715,1.865927,1.319332,0.068091,-0.221649
2,N,-0.402788,2.005598,1.254211,-1.124159,1.062835,1.146655,-1.146354,-0.473888,-0.435411,...,0.659530,0.934619,-1.140030,-0.119123,-0.542781,0.545029,1.504517,-0.005015,-0.188905,-0.587605
3,N,-0.402456,2.208882,-1.891052,-0.444249,-1.740389,-1.655059,3.159319,2.819562,1.202549,...,-1.435248,-1.424458,2.989745,3.038939,1.439360,1.740751,4.623205,3.857313,-0.445902,-0.587605
4,R,-0.402421,-0.579016,0.912816,-1.841070,0.950556,0.930899,-0.196784,-0.196440,0.589198,...,0.419550,0.295876,-0.295922,-0.966482,-0.206592,-0.351213,-1.162070,-0.656634,0.325087,-0.587605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,N,2.545034,-1.275990,-0.847900,0.684308,-0.725203,-0.884581,1.163154,1.368448,0.234471,...,-0.992503,-1.002444,0.112517,1.033503,0.742886,0.417309,0.751916,1.051929,-0.600099,3.254935
190,N,-0.368344,-1.072706,1.617734,-0.088106,1.502593,1.782570,-2.135689,-1.018406,-1.239269,...,0.763869,0.854349,-2.814177,-1.409240,-1.895571,-1.864474,-1.572210,-1.543285,1.610068,-0.221649
191,N,-0.368058,-1.130787,-0.620303,2.053378,-0.644737,-0.649235,-0.698609,-0.727384,-0.265820,...,-0.957724,-0.807405,-0.758820,-0.777507,-0.794637,-1.097714,-0.417592,-0.494316,-0.702898,-0.587605
192,N,-0.660104,-1.014625,-0.073438,1.593167,-0.223692,-0.152711,-1.054101,-1.518810,-1.278699,...,-0.265609,-0.182326,-0.808740,-1.256001,-1.273104,-1.833204,0.188820,-1.428349,0.427885,-0.587605
193,N,-0.366675,-1.188868,-0.222008,1.348030,-0.209657,-0.237594,-1.098637,-0.589658,-0.778831,...,-0.394294,-0.322371,-0.495603,-0.507369,-0.519259,-1.029450,-0.253806,-0.488686,0.325087,-0.587605

In [87]:
db6_standardized.describe()

,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,...,X.24,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33
count,1.940000e+02,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,...,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02,1.940000e+02
mean,-4.120415e-17,0.000000,-2.380684e-16,-6.409535e-16,-3.662591e-17,2.014425e-16,1.410098e-15,-5.493887e-17,1.373472e-17,-4.395110e-16,...,-9.156479e-17,-1.831296e-17,-1.300220e-15,2.014425e-16,-4.395110e-16,2.334902e-16,-7.325183e-17,-3.845721e-16,2.197555e-16,-5.722799e-18
std,1.002587e+00,1.002587,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,...,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00,1.002587e+00
min,-6.897318e-01,-1.334071,-2.039623e+00,-2.756867e+00,-2.006115e+00,-1.724612e+00,-2.211241e+00,-1.927997e+00,-1.870145e+00,-1.963047e+00,...,-1.914164e+00,-1.526247e+00,-2.814177e+00,-1.897365e+00,-2.363827e+00,-3.291193e+00,-2.243595e+00,-1.676517e+00,-1.268289e+00,-5.876049e-01
25%,-3.980890e-01,-0.949283,-7.427941e-01,-6.841831e-01,-7.775997e-01,-7.567590e-01,-7.057664e-01,-6.545292e-01,-7.099352e-01,-6.803797e-01,...,-7.725222e-01,-7.876369e-01,-6.623828e-01,-7.087609e-01,-6.532189e-01,-5.774752e-01,-6.267226e-01,-6.759852e-01,-7.028977e-01,-5.876049e-01
50%,-3.876668e-01,-0.216008,-3.550499e-02,-1.170137e-01,-5.059533e-02,-1.135342e-01,-4.567970e-02,-2.173986e-01,-6.019219e-02,-2.162911e-02,...,-1.264903e-01,-1.823262e-01,-9.850966e-02,-8.550704e-02,-1.999941e-01,1.118060e-03,-1.617619e-01,-1.987651e-01,-1.889054e-01,-4.046268e-01
75%,-3.733815e-01,0.756852,6.883798e-01,5.738808e-01,6.955899e-01,6.370721e-01,6.839944e-01,5.899957e-01,6.245289e-01,5.053123e-01,...,6.864838e-01,4.995396e-01,4.778435e-01,3.580087e-01,6.549658e-01,6.314599e-01,4.903337e-01,5.159510e-01,3.250869e-01,1.443075e-01
max,2.545034e+00,2.266963,3.103436e+00,3.926598e+00,3.149346e+00,3.636374e+00,3.334282e+00,3.368470e+00,3.822720e+00,3.376921e+00,...,3.201922e+00,4.271790e+00,3.570636e+00,4.200045e+00,4.210916e+00,2.463030e+00,4.623205e+00,5.475804e+00,3.666037e+00,4.352803e+00

In [88]:
db6_standardized.to_csv(r'/Users/minhnguyetnguyen/Documents/AISOUP/AutoML/Database/DB6/std_db6.csv', index=False)

In [89]:
from sklearn.preprocessing import MinMaxScaler

# Extract the Class column
class_column = db6.pop('Class')

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Normalize the numeric columns
norm_db6 = pd.DataFrame(scaler.fit_transform(db6), columns=db6.columns)

# Add back the Class column
norm_db6 = pd.concat([class_column, norm_db6], axis=1)
norm_db6

,Class,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,...,X.24,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33
0,N,0.011814,0.241935,0.434542,0.595848,0.413793,0.344948,0.285673,0.216883,0.210069,...,0.371176,0.273322,0.267183,0.140351,0.253067,0.336803,0.219200,0.171127,0.479167,0.185185
1,N,0.000000,0.483871,0.432698,0.000000,0.461887,0.338594,0.622831,0.872621,0.685467,...,0.676411,0.445050,0.570687,0.610208,0.600269,0.904711,0.598462,0.418864,0.270833,0.074074
2,N,0.088706,0.927419,0.640443,0.244291,0.595281,0.535586,0.192026,0.274543,0.252023,...,0.503059,0.424431,0.262208,0.291639,0.276976,0.666679,0.545831,0.233701,0.218750,0.000000
3,N,0.088809,0.983871,0.028888,0.346021,0.051543,0.012974,0.968450,0.896363,0.539745,...,0.093610,0.017556,0.909020,0.809574,0.578454,0.874479,1.000000,0.773711,0.166667,0.000000
4,R,0.088820,0.209677,0.574063,0.137024,0.573503,0.495340,0.363258,0.326927,0.432004,...,0.456152,0.314266,0.394413,0.152669,0.328109,0.510926,0.157500,0.142595,0.322917,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,N,1.000000,0.016129,0.231715,0.514879,0.248457,0.156693,0.608490,0.622386,0.369694,...,0.180150,0.090341,0.458384,0.480674,0.472522,0.644484,0.436231,0.381477,0.135417,0.777778
190,N,0.099354,0.072581,0.711125,0.399308,0.680581,0.654205,0.013624,0.171735,0.110819,...,0.523453,0.410586,0.000000,0.080054,0.071220,0.247943,0.097773,0.018628,0.583333,0.074074
191,N,0.099443,0.056452,0.275968,0.719723,0.264065,0.200593,0.272766,0.226682,0.281813,...,0.186948,0.123980,0.321913,0.183661,0.238669,0.381195,0.265918,0.165289,0.114583,0.000000
192,N,0.009159,0.088710,0.382299,0.650865,0.345735,0.293211,0.208662,0.077256,0.103893,...,0.322230,0.231789,0.314095,0.105186,0.165896,0.253377,0.354228,0.034698,0.343750,0.000000
193,N,0.099870,0.040323,0.353411,0.614187,0.348457,0.277378,0.200631,0.252685,0.191699,...,0.297077,0.207635,0.363139,0.227965,0.280554,0.393058,0.289769,0.166076,0.322917,0.000000

In [90]:
norm_db6.describe()

,X.0,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,...,X.24,X.25,X.26,X.27,X.28,X.29,X.30,X.31,X.32,X.33
count,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,...,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000
mean,0.213225,0.370469,0.396578,0.412491,0.389124,0.321697,0.398743,0.364016,0.328507,0.367614,...,0.374146,0.263235,0.440761,0.311176,0.359531,0.571961,0.326731,0.234402,0.257034,0.118939
std,0.309941,0.278417,0.194940,0.150010,0.194471,0.187015,0.180792,0.189294,0.176113,0.187752,...,0.195968,0.172918,0.157027,0.164428,0.152491,0.174235,0.146005,0.140176,0.203186,0.202936
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.090159,0.106855,0.252151,0.310121,0.238294,0.180536,0.271476,0.240437,0.203801,0.240201,...,0.223148,0.127390,0.337018,0.194936,0.260179,0.471605,0.235462,0.139889,0.114583,0.000000
50%,0.093381,0.310484,0.389674,0.394983,0.379310,0.300519,0.390506,0.322970,0.317934,0.363563,...,0.349422,0.231789,0.425332,0.297152,0.329113,0.572156,0.303174,0.206612,0.218750,0.037037
75%,0.097797,0.580645,0.530424,0.498356,0.524047,0.440532,0.522085,0.475410,0.438211,0.462242,...,0.508328,0.349392,0.515602,0.369890,0.459150,0.681700,0.398137,0.306539,0.322917,0.148148
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [91]:
norm_db6.to_csv(r'/Users/minhnguyetnguyen/Documents/AISOUP/AutoML/Database/DB6/norm_db6.csv', index=False)